"""
Messages displayed in UI or in the logs.
"""

STATUS_READY_TO_START               = "Plug in UART cable and click START"
STATUS_CONN_TO_UART                 = "Connecting to UART"
STATUS_CONN_TO_UART_FAILED          = "Connection to UART failed!"
STATUS_SCAN_SERIAL_NUM              = "Scan the serial number"
STATUS_SCAN_QR_TOP                  = "Scan the TOP data matrix QR code"
STATUS_SCAN_QR_BOTTOM               = "Scan the BOTTOM data matrix QR code"
STATUS_REGISTER_DEVICE              = "Registering device to get MACs"
STATUS_LOADING_UBOOT_SPL_VIA_JTAG   = "Loading U-Boot via JTAG"
STATUS_PROCESS_ERRORED              = "Process errored"
STATUS_WAITING_FOR_UBOOT_SPL_PROMPT = "Waiting for u-boot prompt"
STATUS_LOADING_QSPI_FIRMWARE_TO_MEM = "Loading QSPI firmware into memory"
STATUS_DONE                         = "All tests successful!"
CONN_TO_SERVER_FAILED               = "Connection to server failed"
UI_START_BTN_LABEL_START            = "Start"
UI_START_BTN_LABEL_CONT             = "Continue"
UI_RESET_BTN_LABEL                  = "Reset"
UI_LABEL_SERIAL                     = "Serial number"
UI_LABEL_TOP_QR                     = "Top data matrix (QR code)"
UI_LABEL_BOTTOM_QR                  = "Bottom data matrix (QR code)"
LOG_INFO_UART_CONNECTED             = "Connected to UART"
LOG_INFO_UART_DATA_RECEIVED         = "UART working. Data was received."
LOG_ERROR_UART_FAILED               = "UART connection FAILED:"
LOG_ERROR_UART_WRITE_NOT_OPEN       = "Can not send data via UART. Connection is not open."
LOG_INFO_FIRST_CODE_SCANNED         = "First code scanned:"
LOG_INFO_SECOND_CODE_SCANNED        = "Second code scanned:"
LOG_ERROR_MORE_THAN_2_QR_SCANNED    = "More than 2 dm qr codes scanned somehow!"
LOG_INFO_SERVER_RESPONSE            = "Received response from server:\n"
LOG_INFO_SERVER_ERROR               = "Received ERROR from server:\n"
LOG_INFO_DONE                       = "Done!"
LOG_WRONG_STATE_TO_START_FROM       = "Can not start from the current state:"
LOG_PROCESS_EXITED                  = "Process exited with:"
LOG_PROCESS_ERRORED                 = "Process errored with:"
LOG_PROCESS_EXITED_NON_0_CODE       = "Program exist with non-zero return code!"

# Error messages for ctx.fail()
ERROR_MORE_THAN_2_QR_SCANNED        = "More than 2 QR codes scanned"
ERROR_SERVER_ERROR                  = "Server error"
ERROR_TIMEOUT_LSBP_TCL              = "Timed out waiting for lsbp.tcl to exit"
ERROR_TIMEOUT_UBOOT_SPL_PROMPT      = "Timed out waiting for U-Boot SPL prompt"
ERROR_FAILED_START_USB              = "Failed to start USB"
ERROR_FAILED_LOAD_FIRMWARE_TO_MEM   = "Failed to load firmware to memory"
ERROR_FAILED_PROBE_FLASH            = "Failed to probe flash"
ERROR_FAILED_ERASE_FLASH            = "Failed to erase flash"
ERROR_FAILED_WRITE_FIRMWARE_TO_FLASH = "Failed to write firmware to flash"
ERROR_FAILED_RESET_DEVICE           = "Failed to reset device"
ERROR_TIMEOUT_UBOOT_PROMPT          = "Timed out waiting for U-Boot prompt"
ERROR_FAILED_SET_TIME               = "Failed to set time in U-Boot"
ERROR_FAILED_SET_I2C_BUS            = "Failed to set I2C bus"
ERROR_FAILED_ERASE_EEPROM           = "Failed to erase EEPROM"
ERROR_FAILED_PROGRAM_EEPROM         = "Failed to program EEPROM"
ERROR_SELF_TESTS_FAILED             = "Self tests did not pass"
ERROR_RTC_LOW_VOLTAGE               = "RTC Low Voltage detected"
ERROR_FAILED_STOP_AUTOBOOT          = "Failed to stop autoboot"
ERROR_FAILED_RUN_RECOVERY           = "Failed to run recovery"
ERROR_FAILED_LOGIN_RECOVERY         = "Failed to login to recovery Linux"
ERROR_FAILED_PARTITION_EMMC         = "Failed to partition eMMC"
ERROR_FAILED_CREATE_FILESYSTEM      = "Failed to create filesystem on eMMC"
ERROR_FILESYSTEM_CREATION_INCOMPLETE = "Filesystem creation incomplete"
ERROR_FAILED_MOUNT_USB              = "Failed to mount USB drive"
ERROR_FAILED_WRITE_IMAGE_TO_EMMC    = "Failed to write image to eMMC"
ERROR_DD_COMMAND_FAILED             = "dd command failed"
ERROR_FAILED_BOOT_OPENWRT           = "Failed to boot to OpenWrt"
ERROR_FAILED_GET_OPENWRT_PROMPT     = "Failed to get OpenWrt prompt"
