"""
Messages displayed in UI or in the logs.
"""

STATUS_READY_TO_START               = "Plug in UART cable and click START"
STATUS_CONN_TO_UART                 = "Connecting to UART"
STATUS_CONN_TO_UART_FAILED          = "Connection to UART failed!"
STATUS_SCAN_SERIAL_NUM              = "Scan the serial number"
STATUS_SCAN_QR_TOP                  = "Scan the TOP data matrix QR code"
STATUS_SCAN_QR_BOTTOM               = "Scan the BOTTOM data matrix QR code"
STATUS_REGISTER_DEVICE              = "Registering device to get MACs"
STATUS_LOADING_UBOOT_VIA_JTAG       = "Loading U-Boot via JTAG"
STATUS_CONNECT_CABLES               = "Connect cables"
STATUS_WAITING_FOR_UBOOT_PROMPT     = "Waiting for u-boot prompt"
STATUS_DONE                         = "All tests successful!"
CONN_TO_SERVER_FAILED               = "Connection to server failed"
UI_START_BTN_LABEL_START            = "Start"
UI_START_BTN_LABEL_CONT             = "Continue"
UI_RESET_BTN_LABEL                  = "Reset"
UI_LABEL_SERIAL                     = "Serial number"
UI_LABEL_TOP_QR                     = "Top data matrix (QR code)"
UI_LABEL_BOTTOM_QR                  = "Bottom data matrix (QR code)"
LOG_INFO_UART_CONNECTED             = "Connected to UART"
LOG_INFO_UART_DATA_RECEIVED         = "UART working. Data was received."
LOG_ERROR_UART_FAILED               = "UART connection FAILED:"
LOG_ERROR_UART_WRITE_NOT_OPEN       = "Can not send data via UART. Connection is not open."
LOG_INFO_FIRST_CODE_SCANNED         = "First code scanned:"
LOG_INFO_SECOND_CODE_SCANNED        = "Second code scanned:"
LOG_ERROR_MORE_THAN_2_QR_SCANNED    = "More than 2 dm qr codes scanned somehow!"
LOG_INFO_SERVER_RESPONSE            = "Received response from server:\n"
LOG_INFO_SERVER_ERROR               = "Received ERROR from server:\n"
LOG_INFO_DONE                       = "Done!"
LOG_WRONG_STATE_TO_START_FROM       = "Can not start from the current state:"
