"""
Messages displayed in UI or in the logs.
"""

status_ready_to_start               = "Plug in UART cable and click START"
status_conn_to_uart                 = "Connecting to UART"
status_conn_to_uart_failed          = "Connection to UART failed!"
status_scan_qr_top                  = "Scan the TOP data matrix QR code"
status_scan_qr_bottom               = "Scan the BOTTOM data matrix QR code"
status_get_ser_macs                 = "Fetching serial and MACs"
status_connect_cables               = "Connect cables"
status_done                         = "All tests successful!"
ui_start_btn_label_start            = "Start"
ui_start_btn_label_cont             = "Continue"
ui_reset_btn_label                  = "Reset"
ui_label_top_qr                     = "Top data matrix (QR code)"
ui_label_bottom_qr                  = "Top data matrix (QR code)"
ui_label_qr_group                   = "Data matrix QR codes"
log_info_uart_connected             = "Connected to UART"
log_error_uart_failed               = "UART connection FAILED: "
log_info_first_code_scanned         = "First code scanned: "
log_info_second_code_scanned        = "Second code scanned: "
log_error_wrong_state_to_start_from = "Can not start from state: "
log_error_more_than_2_qr_scanned    = "More than 2 dm qr codes scanned somehow!"
log_info_server_response            = "Recevied response from server:\n"
log_info_server_error               = "Recevied ERROR from server:\n"
log_info_done                       = "Done!"
log_wrong_state_to_start_from       = "Can not start from the current state: "